version: '3.1'

services:
        mariadb:
                image: mariadb:10.3.22
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=root
        webapi:
                image: webapi
                ports: 
                        - "8080:8080"
                depends_on:
                        - mariadb
                environment:
                        - ASPNETCORE_ENVIRONMENT=Production
                        - DB_SERVER=mariadb
                        - DB_USER=root
                        - DB_PASSWORD=root
                        - DB_DATABASE=animalchipization

