version: '3.1'

services:
        mariadb:
                image: mariadb:10.3.22
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=root
        webapi:
                image: webapi
                build:
                        context: .
                ports: 
                        - "8080:8080"
                depends_on:
                        - mariadb
                environment:
                        - ASPNETCORE_ENVIRONMENT=Production
                        - DB_SERVER=mariadb
                        - DB_USER=root
                        - DB_PASSWORD=root
                        - DB_DATABASE=animalchipization
        tests:
                image: mrexpen/planet_olymp_phase1
                ports:
                        - "8090:8080"
                depends_on:
                        - webapi
                environment:
                        - SERVER_URL=http://webapi:8080
                        - STAGE=all

